//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "album")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub release_date: Date,
    pub album_type: String,
    pub images: Vec<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub colors: Option<Json>,
    pub display: bool,
    pub updated: Option<Date>,
    pub sharing_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::artist_albums::Entity")]
    ArtistAlbums,
    #[sea_orm(has_many = "super::track::Entity")]
    Track,
}

impl Related<super::artist_albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArtistAlbums.def()
    }
}

impl Related<super::track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Track.def()
    }
}

impl Related<super::artist::Entity> for Entity {
    fn to() -> RelationDef {
        super::artist_albums::Relation::Artist.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::artist_albums::Relation::Album.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
