//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub mod prelude;

pub mod album;
pub mod artist;
pub mod artist_albums;
pub mod artist_tracks;
pub mod daily_streams;
pub mod follower_instance;
pub mod mikro_orm_migrations;
pub mod monthly_listeners;
pub mod track;
