//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::album::Entity as Album;
pub use super::artist::Entity as Artist;
pub use super::artist_albums::Entity as ArtistAlbums;
pub use super::artist_tracks::Entity as ArtistTracks;
pub use super::daily_streams::Entity as DailyStreams;
pub use super::follower_instance::Entity as FollowerInstance;
pub use super::mikro_orm_migrations::Entity as MikroOrmMigrations;
pub use super::monthly_listeners::Entity as MonthlyListeners;
pub use super::track::Entity as Track;
